use statik_core::prelude::*;
use statik_derive::*;

#[derive(Debug, Packet)]
#[packet(id = 0x00, state = State::Login)]
pub struct S2CDisconnect {
    /// Why the client was disconnected before login success.
    pub reason: Chat,
}

#[derive(Debug, Packet)]
#[packet(id = 0x01, state = State::Login)]
pub struct S2CEncryptionRequest {
    /// Appears to be unused and sent as empty to the client. 20 bytes long.
    pub server_id: String,
    /// The server's public key, as bytes
    pub public_key: Vec<u8>,
    /// A sequence of random bytes generated by the server. Always of Length
    /// 4 when send by a notchian server.
    pub verify_token: Vec<u8>,
}

use uuid::Uuid;

/// One signed property entry on a [`S2CLoginSuccess`] game profile.
///
/// See Mojang's `com.mojang.authlib.properties.Property` and
/// [wiki.vg](https://wiki.vg/Protocol#Game_Profile). `signature` is `None`
/// for unsigned properties (a `"SignedProperty"` absent the signature half).
#[derive(Debug, Encode, Decode)]
pub struct Property {
    /// Property name, e.g. `"textures"`.
    pub name: String,
    /// Property value (base64-encoded payload).
    pub value: String,
    /// Optional base64 signature; absent for unsigned properties.
    pub signature: Option<String>,
}

#[derive(Debug, Packet)]
#[packet(id = 0x02, state = State::Login)]
pub struct S2CLoginSuccess {
    pub uuid: Uuid,
    pub username: String,
    pub properties: Vec<Property>,
}

#[derive(Debug, Packet)]
#[packet(id = 0x03, state = State::Login)]
pub struct S2CSetCompression {
    pub threshold: VarInt,
}

#[derive(Debug, Packet)]
#[packet(id = 0x04, state = State::Login)]
pub struct S2CLoginPluginRequest {
    pub message_id: VarInt,
    /// See: https://wiki.vg/Protocol#Identifier
    pub channel: String,
    pub data: Vec<u8>,
}
